apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gocd-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: gocd-agent
    spec:
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      containers:
      - name: gocd-agent
        imagePullPolicy: Always
        image: danielsomerfield/gocd-agent-java
        ports:
        - containerPort: 8080
        env:
          - name: GO_EA_SERVER_URL
            value: https://gocd-server:8154/go
          - name: DOCKER_API_VERSION
            value: "1.23"
          - name: GO_EA_AUTO_REGISTER_KEY
            valueFrom:
              secretKeyRef:
                name: go-secrets
                key: autoregister-key
        command: ["/bin/sh"]
        #TODO: this is probably a bad idea, particularly if the core kubernetes cluster is using the same docker runtime
        args: ['-c', 'chmod 0777 /var/run/docker.sock; ./docker-entrypoint.sh'] 
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
            readOnly: false