apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pipeline-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: pipeline-service
        app: pipeline-service
    spec:
      volumes:
        - name: vault-certificate
          hostPath:
            path: /vault-certificate
      containers:
      - name: pipeline-service
        imagePullPolicy: Always
        image: ${REGISTRY_USERNAME}/pipeline-service
        ports:
        - containerPort: 5000
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: pipelineservice-secrets
                key: vault-token
        volumeMounts:
          - mountPath: /etc/vault/certificates
            name: vault-certificate
            readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: pipeline-service
  labels:
    run: pipeline-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    run: pipeline-service