apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: vault
    spec:
      containers:
      - name: vault
        imagePullPolicy: Always
        image: danielsomerfield/vault
        ports:
        - containerPort: 8200
---

apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    run: vault
spec:
  type: LoadBalancer
  ports:
  - port: 8200
    protocol: TCP
    name: api
    targetPort: 8200
  selector:
    run: vault